name: 毎日イベント更新

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前0時
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: ライブラリをインストール
        run: pip install feedparser

      - name: スクリプトを実行
        run: python scripts/fetch_events.py

      - name: 更新をコミット＆プッシュ
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/events.json
          git commit -m \"Update events.json\" || echo \"No changes\"
          git push
